# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ck3KPVicYds2MaLXPJTZlRKWXXVstwGk
"""

from collections import deque

def bfsofgraph(v, adj):
    bfs = []
    vis = [False] * v
    q = deque()

    q.append(0)
    vis[0] = True

    while q:
        node = q.popleft()
        bfs.append(node)

        for it in adj[node]:
            if not vis[it]:
                vis[it] = True
                q.append(it)

    return bfs

v = int(input())
e = int(input())

adj = [[] for _ in range(v)]

for _ in range(e):
    u, v1 = map(int, input().split())
    adj[u].append(v1)
    adj[v1].append(u)

result = bfsofgraph(v, adj)
print(*result)

def dfs(node,adj,vis,ans):
  vis[node]=True
  ans.append(node)
  for it in adj[node]:
    if not vis[it]:
      dfs(it,adj,vis,ans)
def dfsofgraph(v,adj):
  vis=[False]*v
  ans=[]
  dfs(0,adj,vis,ans)
  return ans
v = int(input())
e = int(input())

adj = [[] for _ in range(v)]

for _ in range(e):
    u, v1 = map(int, input().split())
    adj[u].append(v1)
    adj[v1].append(u)

result = dfsofgraph(v, adj)
print(*result)