# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlmT460cHXZwMdPrao0lBf2Zm9CzDXbT
"""

grid = [
    ['00', '01', '02'],
    ['10', '11', '12'],
    ['20', '21', '22']
]

visited = [[False] * 3 for _ in range(3)]

directions = [
    (0, 1),   # right
    (1, 0),   # down
    (0, -1),  # left
    (-1, 0)   # up
]

all_paths = []
min_cost = float('inf')
min_paths = []


def find_paths(row, col, dest_row, dest_col, path, cost):
    global min_cost, min_paths

    # Destination reached
    if row == dest_row and col == dest_col:

        # Store every path
        all_paths.append((path.copy(), cost))

        # Find minimum cost
        if cost < min_cost:
            min_cost = cost
            min_paths = [path.copy()]

        elif cost == min_cost:
            min_paths.append(path.copy())

        return

    visited[row][col] = True

    for dr, dc in directions:

        new_row = row + dr
        new_col = col + dc

        if (0 <= new_row < 3 and
            0 <= new_col < 3 and
            not visited[new_row][new_col]):

            find_paths(
                new_row,
                new_col,
                dest_row,
                dest_col,
                path + [grid[new_row][new_col]],
                cost + 1
            )

    # Backtracking
    visited[row][col] = False


# Input source
source = input("Enter source (row col): ").split()
src_row = int(source[0])
src_col = int(source[1])

# Input destination
destination = input("Enter destination (row col): ").split()
dest_row = int(destination[0])
dest_col = int(destination[1])


# Validate input
if not (0 <= src_row < 3 and 0 <= src_col < 3):
    print("Invalid source")

elif not (0 <= dest_row < 3 and 0 <= dest_col < 3):
    print("Invalid destination")

else:

    find_paths(
        src_row,
        src_col,
        dest_row,
        dest_col,
        [grid[src_row][src_col]],
        0
    )

    # Print all possible paths
    if len(all_paths) == 0:
        print("No path found")

    else:
        print("\n===== ALL POSSIBLE PATHS =====\n")

        for i, (path, cost) in enumerate(all_paths, 1):
            print(
                "Path", i, ":",
                " -> ".join(path),
                "| Cost:", cost
            )

        # Print minimum cost
        print("\n===== MINIMUM COST =====")
        print("Minimum Cost:", min_cost)

        # Print minimum-cost paths
        print("\n===== MINIMUM COST PATH(S) =====\n")

        for i, path in enumerate(min_paths, 1):
            print(
                "Minimum Path", i, ":",
                " -> ".join(path),
                "| Cost:", min_cost
            )